### ISSUE TITLE
setTimeout: Doesn't recognize callback

### ISSUE THREAD

**Issue by mmathys** [Trrnts/Trrnts#1]
When running only the the crawler.js by running the example usage snippet

```
 var crawl = require('./crawl');
 crawl.init(function () {
   crawl('8CA378DBC8F62E04DF4A4A0114B66018666C17CD', function (err, result) {
     console.log(result);
     process.exit(1);
   });
 });

```

it doesn't recognize the callback function as in [Line 171](https://github.com/Trrnts/Trrnts/blob/master/workers/crawl.js#L171), and the output also says that it didn't find any peers. Can't I run the crawl.js alone?

```
Crawling 8CA378DBC8F62E04DF4A4A0114B66018666C17CD...
Done crawling 8CA378DBC8F62E04DF4A4A0114B66018666C17CD.
Found 0 peers for 8CA378DBC8F62E04DF4A4A0114B66018666C17CD.
Found 0 nodes for 8CA378DBC8F62E04DF4A4A0114B66018666C17CD.
Successfully deleted crawl job for 8CA378DBC8F62E04DF4A4A0114B66018666C17CD.

/home/max/code/crawler/trrnts.js:171
    callback(null, {
    ^
TypeError: undefined is not a function
    at null._onTimeout (/home/max/code/crawler/trrnts.js:171:5)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

(note that I renamed crawl.js to trrnts.js)

**Comment by alexanderGugel** [comment]
As a heads up, there is also a standalone version of the crawler: https://gist.github.com/alexanderGugel/a27ab36ac6ced1bcdb64
